// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: l8notify.proto

package l8notify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Channel types for notification delivery.
// Consumers extend behavior via the CUSTOM channel + custom sender registration.
type NotifyChannel int32

const (
	NotifyChannel_NOTIFY_CHANNEL_UNSPECIFIED NotifyChannel = 0
	NotifyChannel_NOTIFY_CHANNEL_EMAIL       NotifyChannel = 1
	NotifyChannel_NOTIFY_CHANNEL_WEBHOOK     NotifyChannel = 2
	NotifyChannel_NOTIFY_CHANNEL_SLACK       NotifyChannel = 3
	NotifyChannel_NOTIFY_CHANNEL_PAGERDUTY   NotifyChannel = 4
	NotifyChannel_NOTIFY_CHANNEL_CUSTOM      NotifyChannel = 5
)

// Enum value maps for NotifyChannel.
var (
	NotifyChannel_name = map[int32]string{
		0: "NOTIFY_CHANNEL_UNSPECIFIED",
		1: "NOTIFY_CHANNEL_EMAIL",
		2: "NOTIFY_CHANNEL_WEBHOOK",
		3: "NOTIFY_CHANNEL_SLACK",
		4: "NOTIFY_CHANNEL_PAGERDUTY",
		5: "NOTIFY_CHANNEL_CUSTOM",
	}
	NotifyChannel_value = map[string]int32{
		"NOTIFY_CHANNEL_UNSPECIFIED": 0,
		"NOTIFY_CHANNEL_EMAIL":       1,
		"NOTIFY_CHANNEL_WEBHOOK":     2,
		"NOTIFY_CHANNEL_SLACK":       3,
		"NOTIFY_CHANNEL_PAGERDUTY":   4,
		"NOTIFY_CHANNEL_CUSTOM":      5,
	}
)

func (x NotifyChannel) Enum() *NotifyChannel {
	p := new(NotifyChannel)
	*p = x
	return p
}

func (x NotifyChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_l8notify_proto_enumTypes[0].Descriptor()
}

func (NotifyChannel) Type() protoreflect.EnumType {
	return &file_l8notify_proto_enumTypes[0]
}

func (x NotifyChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyChannel.Descriptor instead.
func (NotifyChannel) EnumDescriptor() ([]byte, []int) {
	return file_l8notify_proto_rawDescGZIP(), []int{0}
}

// Status of a delivery attempt.
type DeliveryStatus int32

const (
	DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED DeliveryStatus = 0
	DeliveryStatus_DELIVERY_STATUS_PENDING     DeliveryStatus = 1
	DeliveryStatus_DELIVERY_STATUS_SENT        DeliveryStatus = 2
	DeliveryStatus_DELIVERY_STATUS_FAILED      DeliveryStatus = 3
	DeliveryStatus_DELIVERY_STATUS_RETRYING    DeliveryStatus = 4
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "DELIVERY_STATUS_UNSPECIFIED",
		1: "DELIVERY_STATUS_PENDING",
		2: "DELIVERY_STATUS_SENT",
		3: "DELIVERY_STATUS_FAILED",
		4: "DELIVERY_STATUS_RETRYING",
	}
	DeliveryStatus_value = map[string]int32{
		"DELIVERY_STATUS_UNSPECIFIED": 0,
		"DELIVERY_STATUS_PENDING":     1,
		"DELIVERY_STATUS_SENT":        2,
		"DELIVERY_STATUS_FAILED":      3,
		"DELIVERY_STATUS_RETRYING":    4,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_l8notify_proto_enumTypes[1].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_l8notify_proto_enumTypes[1]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_l8notify_proto_rawDescGZIP(), []int{1}
}

// A delivery target: where and how to send a notification.
// Embedded in consumer-specific policy types (not a Prime Object).
type NotifyTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetId string        `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Channel  NotifyChannel `protobuf:"varint,2,opt,name=channel,proto3,enum=l8notify.NotifyChannel" json:"channel,omitempty"`
	Endpoint string        `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"` // email address, webhook URL, Slack webhook URL, etc.
	Template string        `protobuf:"bytes,4,opt,name=template,proto3" json:"template,omitempty"` // message template with {{key}} placeholders
}

func (x *NotifyTarget) Reset() {
	*x = NotifyTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8notify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyTarget) ProtoMessage() {}

func (x *NotifyTarget) ProtoReflect() protoreflect.Message {
	mi := &file_l8notify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyTarget.ProtoReflect.Descriptor instead.
func (*NotifyTarget) Descriptor() ([]byte, []int) {
	return file_l8notify_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyTarget) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *NotifyTarget) GetChannel() NotifyChannel {
	if x != nil {
		return x.Channel
	}
	return NotifyChannel_NOTIFY_CHANNEL_UNSPECIFIED
}

func (x *NotifyTarget) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *NotifyTarget) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

// SMTP connection configuration.
// Consumers store this in their own service; l8notify reads it as a struct.
type SmtpConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host        string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port        int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username    string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password    string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	UseTls      bool   `protobuf:"varint,5,opt,name=use_tls,json=useTls,proto3" json:"use_tls,omitempty"`
	FromAddress string `protobuf:"bytes,6,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	FromName    string `protobuf:"bytes,7,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
}

func (x *SmtpConfig) Reset() {
	*x = SmtpConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8notify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmtpConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmtpConfig) ProtoMessage() {}

func (x *SmtpConfig) ProtoReflect() protoreflect.Message {
	mi := &file_l8notify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmtpConfig.ProtoReflect.Descriptor instead.
func (*SmtpConfig) Descriptor() ([]byte, []int) {
	return file_l8notify_proto_rawDescGZIP(), []int{1}
}

func (x *SmtpConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SmtpConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SmtpConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SmtpConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SmtpConfig) GetUseTls() bool {
	if x != nil {
		return x.UseTls
	}
	return false
}

func (x *SmtpConfig) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *SmtpConfig) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

// Webhook endpoint configuration.
// Consumers store this in their own service; l8notify reads it as a struct.
type WebhookConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url        string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Secret     string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`                            // HMAC-SHA256 signing secret
	RetryCount int32  `protobuf:"varint,3,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"` // max retries (default 3)
	TimeoutMs  int32  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`    // HTTP timeout (default 5000)
}

func (x *WebhookConfig) Reset() {
	*x = WebhookConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8notify_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebhookConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookConfig) ProtoMessage() {}

func (x *WebhookConfig) ProtoReflect() protoreflect.Message {
	mi := &file_l8notify_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookConfig.ProtoReflect.Descriptor instead.
func (*WebhookConfig) Descriptor() ([]byte, []int) {
	return file_l8notify_proto_rawDescGZIP(), []int{2}
}

func (x *WebhookConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebhookConfig) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *WebhookConfig) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *WebhookConfig) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// Result of a single delivery attempt.
type DeliveryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       DeliveryStatus `protobuf:"varint,1,opt,name=status,proto3,enum=l8notify.DeliveryStatus" json:"status,omitempty"`
	HttpStatus   int32          `protobuf:"varint,2,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"` // for webhook/slack (0 for email)
	ErrorMessage string         `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Attempt      int32          `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`             // 1-based attempt number
	SentAt       int64          `protobuf:"varint,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"` // Unix timestamp
}

func (x *DeliveryResult) Reset() {
	*x = DeliveryResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8notify_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryResult) ProtoMessage() {}

func (x *DeliveryResult) ProtoReflect() protoreflect.Message {
	mi := &file_l8notify_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryResult.ProtoReflect.Descriptor instead.
func (*DeliveryResult) Descriptor() ([]byte, []int) {
	return file_l8notify_proto_rawDescGZIP(), []int{3}
}

func (x *DeliveryResult) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED
}

func (x *DeliveryResult) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *DeliveryResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DeliveryResult) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *DeliveryResult) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

// Configuration for the escalation scheduler.
// Consumers embed this in their own escalation policy types.
type EscalationStep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StepId          string        `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	StepOrder       int32         `protobuf:"varint,2,opt,name=step_order,json=stepOrder,proto3" json:"step_order,omitempty"`
	DelayMinutes    int32         `protobuf:"varint,3,opt,name=delay_minutes,json=delayMinutes,proto3" json:"delay_minutes,omitempty"`
	Channel         NotifyChannel `protobuf:"varint,4,opt,name=channel,proto3,enum=l8notify.NotifyChannel" json:"channel,omitempty"`
	Endpoint        string        `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	MessageTemplate string        `protobuf:"bytes,6,opt,name=message_template,json=messageTemplate,proto3" json:"message_template,omitempty"`
}

func (x *EscalationStep) Reset() {
	*x = EscalationStep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8notify_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EscalationStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscalationStep) ProtoMessage() {}

func (x *EscalationStep) ProtoReflect() protoreflect.Message {
	mi := &file_l8notify_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscalationStep.ProtoReflect.Descriptor instead.
func (*EscalationStep) Descriptor() ([]byte, []int) {
	return file_l8notify_proto_rawDescGZIP(), []int{4}
}

func (x *EscalationStep) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *EscalationStep) GetStepOrder() int32 {
	if x != nil {
		return x.StepOrder
	}
	return 0
}

func (x *EscalationStep) GetDelayMinutes() int32 {
	if x != nil {
		return x.DelayMinutes
	}
	return 0
}

func (x *EscalationStep) GetChannel() NotifyChannel {
	if x != nil {
		return x.Channel
	}
	return NotifyChannel_NOTIFY_CHANNEL_UNSPECIFIED
}

func (x *EscalationStep) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *EscalationStep) GetMessageTemplate() string {
	if x != nil {
		return x.MessageTemplate
	}
	return ""
}

var File_l8notify_proto protoreflect.FileDescriptor

var file_l8notify_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6c, 0x38, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6c, 0x38, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x22, 0x96, 0x01, 0x0a, 0x0c, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6c, 0x38, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x22, 0xc5, 0x01, 0x0a, 0x0a, 0x53, 0x6d, 0x74, 0x70, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x6c, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x73, 0x65, 0x54, 0x6c, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x66,
	0x72, 0x6f, 0x6d, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x79, 0x0a, 0x0d, 0x57,
	0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x74, 0x72, 0x79, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x74,
	0x72, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x22, 0xbb, 0x01, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6c, 0x38, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x68,
	0x74, 0x74, 0x70, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x68, 0x74, 0x74, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x65, 0x6e, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65,
	0x6e, 0x74, 0x41, 0x74, 0x22, 0xe7, 0x01, 0x0a, 0x0e, 0x45, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x65, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x65, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x65, 0x70, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x65, 0x70, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x65, 0x70, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x23, 0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x69, 0x6e,
	0x75, 0x74, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6c, 0x38, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x07,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2a, 0xb8,
	0x01, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x1e, 0x0a, 0x1a, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e,
	0x45, 0x4c, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x18, 0x0a, 0x14, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e,
	0x45, 0x4c, 0x5f, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x4e, 0x4f,
	0x54, 0x49, 0x46, 0x59, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x57, 0x45, 0x42,
	0x48, 0x4f, 0x4f, 0x4b, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59,
	0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x53, 0x4c, 0x41, 0x43, 0x4b, 0x10, 0x03,
	0x12, 0x1c, 0x0a, 0x18, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e,
	0x45, 0x4c, 0x5f, 0x50, 0x41, 0x47, 0x45, 0x52, 0x44, 0x55, 0x54, 0x59, 0x10, 0x04, 0x12, 0x19,
	0x0a, 0x15, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c,
	0x5f, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x10, 0x05, 0x2a, 0xa2, 0x01, 0x0a, 0x0e, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x1b,
	0x44, 0x45, 0x4c, 0x49, 0x56, 0x45, 0x52, 0x59, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b, 0x0a,
	0x17, 0x44, 0x45, 0x4c, 0x49, 0x56, 0x45, 0x52, 0x59, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x44, 0x45,
	0x4c, 0x49, 0x56, 0x45, 0x52, 0x59, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x45,
	0x4e, 0x54, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x44, 0x45, 0x4c, 0x49, 0x56, 0x45, 0x52, 0x59,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03,
	0x12, 0x1c, 0x0a, 0x18, 0x44, 0x45, 0x4c, 0x49, 0x56, 0x45, 0x52, 0x59, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x52, 0x45, 0x54, 0x52, 0x59, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x42, 0x12,
	0x5a, 0x10, 0x2e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6c, 0x38, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_l8notify_proto_rawDescOnce sync.Once
	file_l8notify_proto_rawDescData = file_l8notify_proto_rawDesc
)

func file_l8notify_proto_rawDescGZIP() []byte {
	file_l8notify_proto_rawDescOnce.Do(func() {
		file_l8notify_proto_rawDescData = protoimpl.X.CompressGZIP(file_l8notify_proto_rawDescData)
	})
	return file_l8notify_proto_rawDescData
}

var file_l8notify_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_l8notify_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_l8notify_proto_goTypes = []interface{}{
	(NotifyChannel)(0),     // 0: l8notify.NotifyChannel
	(DeliveryStatus)(0),    // 1: l8notify.DeliveryStatus
	(*NotifyTarget)(nil),   // 2: l8notify.NotifyTarget
	(*SmtpConfig)(nil),     // 3: l8notify.SmtpConfig
	(*WebhookConfig)(nil),  // 4: l8notify.WebhookConfig
	(*DeliveryResult)(nil), // 5: l8notify.DeliveryResult
	(*EscalationStep)(nil), // 6: l8notify.EscalationStep
}
var file_l8notify_proto_depIdxs = []int32{
	0, // 0: l8notify.NotifyTarget.channel:type_name -> l8notify.NotifyChannel
	1, // 1: l8notify.DeliveryResult.status:type_name -> l8notify.DeliveryStatus
	0, // 2: l8notify.EscalationStep.channel:type_name -> l8notify.NotifyChannel
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_l8notify_proto_init() }
func file_l8notify_proto_init() {
	if File_l8notify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_l8notify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8notify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmtpConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8notify_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebhookConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8notify_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliveryResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8notify_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EscalationStep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_l8notify_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l8notify_proto_goTypes,
		DependencyIndexes: file_l8notify_proto_depIdxs,
		EnumInfos:         file_l8notify_proto_enumTypes,
		MessageInfos:      file_l8notify_proto_msgTypes,
	}.Build()
	File_l8notify_proto = out.File
	file_l8notify_proto_rawDesc = nil
	file_l8notify_proto_goTypes = nil
	file_l8notify_proto_depIdxs = nil
}
